# Generated by Django 4.2.2 on 2023-06-14 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTitular', models.CharField(max_length=100, verbose_name='Nome do Titular')),
                ('numeroCartao', models.CharField(max_length=30, verbose_name='Número do Cartão')),
                ('validade', models.DateTimeField(verbose_name='Validade')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
            ],
            options={
                'verbose_name_plural': 'Cartões',
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroConta', models.CharField(max_length=6, unique=True, verbose_name='Número da Conta')),
                ('titular', models.CharField(max_length=45, verbose_name='Titular')),
                ('agencia', models.IntegerField(verbose_name='Agência')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('senha', models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha')),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cartao', verbose_name='Cartão')),
            ],
            options={
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('dataPagamento', models.DateField(verbose_name='DataPagamento')),
                ('dataVencimento', models.DateField(verbose_name='DataVencimento')),
            ],
            options={
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de pagamento')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=100, verbose_name='Mensagem')),
                ('notificacoesAtivas', models.BooleanField(blank=True, null=True, verbose_name='Status')),
                ('data_envio', models.DateTimeField(verbose_name='Entrada')),
                ('notificacaoPagamento', models.BooleanField(blank=True, null=True, verbose_name='Notificação do Pagamento')),
                ('intervaloNotificacoes', models.IntegerField(blank=True, null=True, verbose_name='Intervalo de Notificações')),
                ('diasAntesVencimento', models.IntegerField(blank=True, null=True, verbose_name='diasAntesVencimento')),
            ],
            options={
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_cliente', verbose_name='Foto')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('contaBancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contabancaria', verbose_name='Conta bancária')),
            ],
            options={
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('geracaoRelatorio', models.DateField(verbose_name='Relatório gerado')),
                ('nomeItens', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='core.despesas', verbose_name='Título da conta')),
            ],
            options={
                'verbose_name_plural': 'Relatorios',
            },
        ),
        migrations.AddField(
            model_name='despesas',
            name='notificacaoDespesas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notificacao', verbose_name='Notificacao'),
        ),
        migrations.AddField(
            model_name='despesas',
            name='pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formapagamento', verbose_name='FormaPagamento'),
        ),
    ]
