# Generated by Django 4.2.2 on 2023-06-17 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contabancaria',
            old_name='banco',
            new_name='conta',
        ),
        migrations.RenameField(
            model_name='contabancaria',
            old_name='titular',
            new_name='proprietario',
        ),
    ]
