# Generated by Django 4.2.2 on 2023-06-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_banco_contabancaria_conta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='numeroConta',
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='conta',
            field=models.CharField(max_length=100, verbose_name='Número da Conta'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='proprietario',
            field=models.CharField(max_length=45, verbose_name='Proprietário'),
        ),
    ]
