# Generated by Django 4.2.2 on 2023-06-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contabancaria_numeroconta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contaBancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contabancaria', verbose_name='Número da Conta'),
        ),
    ]
