# Generated by Django 4.2.2 on 2023-06-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contaBancaria',
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='Usuário'),
        ),
    ]
