# Generated by Django 4.2.2 on 2023-06-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_usuario_contabancaria_contabancaria_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contaBancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contabancaria', verbose_name='Número da Conta'),
        ),
    ]
