# Generated by Django 4.2.2 on 2023-06-18 23:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usuario_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo da Despesa'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='tipo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
