# Generated by Django 4.2.2 on 2023-06-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_despesas_nome_alter_formapagamento_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
