# Generated by Django 4.2.2 on 2023-06-19 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_formapagamento_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'verbose_name_plural': 'FormasDePagamentos'},
        ),
        migrations.AlterField(
            model_name='despesas',
            name='notificacaoDespesas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.notificacao', verbose_name='Notificacao'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formapagamento', verbose_name='FormaPagamento'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='tipo',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nome'),
        ),
    ]
