# Generated by Django 4.2.2 on 2023-06-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_tipo_formapagamento_tipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagamento',
            name='tipos',
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='tipo',
            field=models.JSONField(blank=True, max_length=20, null=True, verbose_name='Tipo de pagamento'),
        ),
    ]
