# Generated by Django 4.2.2 on 2023-06-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_formapagamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario', verbose_name='id usuário'),
        ),
    ]
