# Generated by Django 4.2.2 on 2023-06-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_formapagamento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id pagamento'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='tipo',
            field=models.CharField(max_length=20, verbose_name='Tipo de pagamento'),
        ),
    ]
