# Generated by Django 4.2.2 on 2023-06-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_despesas_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesas',
            name='id_usuario',
        ),
    ]
