# Generated by Django 4.2.2 on 2023-06-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_formapagamento_id_alter_formapagamento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de pagamento'),
        ),
    ]
