# Generated by Django 4.2.2 on 2023-06-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_contabancaria_id_remove_usuario_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='id_contaBancaria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
