# Generated by Django 4.2.2 on 2023-06-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_despesas_id_despesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
